### ISSUE TITLE
Add readme with basic make instructions

### ISSUE THREAD

**Issue by antitoxic** [pcloudcom/pfs#1]
I got dependencies issues with fedora before "make"-ing the source. 

I needed to install: 

```
openssl-devel
fuse
```

Probably something something a must-have but it is not included in fedora after a clean install. And the time after clean install is the common time to install sync software like pcloud.

Pozdravi,
Toni :)

**Comment by pcloudcom** [comment]
We still don't  have packaging for Fedora - the debian build there does require those packages. I'll add something to the readme.

**Comment by antitoxic** [comment]
And possible after the make + install instr.:

```
mount.pfs --auth <token you can get reading the description here https://docs.pcloud.com/methods/intro/authentication.html> /path/to/mount/point
```

Could have saved me some time :)
